# Generated by Django 2.1.1 on 2018-09-13 14:18

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationalQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=quotes.models.upload_to, verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Inspirational Quote',
                'verbose_name_plural': 'Inspirational Quotes',
            },
        ),
    ]
