# Generated by Django 2.1.1 on 2018-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('imported', 'Imported'), ('published', 'Published'), ('not_listed', 'Not Listed'), ('expired', 'Expired')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
