# Generated by Django 2.1.1 on 2018-09-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_copy_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
    ]
