# Generated by Django 2.1.2 on 2018-10-03 00:27

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20181002_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, to='movies.Category', verbose_name='Categories'),
        ),
    ]
