# Generated by Django 2.1.1 on 2018-09-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_add_top_250_movies_from_imdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
