# Generated by Django 2.1.1 on 2018-09-18 04:12

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=locations.models.upload_to),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(help_text='The term slug comes from newspaper editing and it means a short string without any special characters; just letters, numbers, underscores, and hyphens. Slugs are generally used to create unique URLs.', verbose_name='slug'),
        ),
    ]
