# Generated by Django 2.1.1 on 2018-09-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationalquote',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('lt', 'Lietuvių kalba')], max_length=5, verbose_name='Language'),
        ),
    ]
