# Generated by Django 2.1.1 on 2018-09-30 05:54

from django.db import migrations, models
import django.db.models.deletion
import editorial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='editorial_editorialcontent', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='Website')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to=editorial.models.upload_to, verbose_name='Image')),
                ('image_caption', models.TextField(blank=True, verbose_name='Image Caption')),
                ('css_class', models.CharField(blank=True, max_length=255, verbose_name='CSS Class')),
            ],
            options={
                'verbose_name': 'Editorial content',
                'verbose_name_plural': 'Editorial contents',
                'ordering': ['title'],
            },
            bases=('cms.cmsplugin',),
        ),
    ]
