# Generated by Django 2.1.1 on 2018-09-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street address')),
                ('street2', models.CharField(blank=True, max_length=255, verbose_name='street address (line 2)')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='city')),
                ('country', models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('LT', 'Lithuania')], max_length=2, verbose_name='country')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude (Lat.) is the angle between any point and the equator (north pole is at 90°; south pole is at -90°).', null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Longitude (Long.) is the angle east or west of a point on Earth at Greenwich (UK), which is the international zero-longitude point (longitude = 0°). The anti-meridian of Greenwich (the opposite side of the planet) is both 180° (to the east) and -180° (to the west).', null=True, verbose_name='longitude')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
