# Generated by Django 2.1.1 on 2018-09-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Curriculum Vitae',
                'verbose_name_plural': 'Curricula Vitarum',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From')),
                ('till_date', models.DateField(blank=True, null=True, verbose_name='Till')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('skills', models.TextField(blank=True, verbose_name='Skills gained')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CurriculumVitae')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ('-from_date',),
            },
        ),
    ]
